name: Bank News Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:

  crawl:

    runs-on: ubuntu-latest

    steps:

      - name: 下载代码
        uses: actions/checkout@v4

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 执行采集
        env:
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          QQ_AUTH_CODE: ${{ secrets.QQ_AUTH_CODE }}
        run: |
          python main.py

      - name: 保存Excel
        uses: actions/upload-artifact@v4
        with:
          name: bank-news
          path: 银行资讯汇总.xlsx