name: Test Trigger

on:
  workflow_dispatch:

  schedule:
    - cron: '7/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 显示触发方式
        run: |
          echo "event=${{ github.event_name }}"
          date

      - name: 输出测试文件
        run: |
          echo "hello github actions"