name: Test Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/8 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger info
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Time: $(date -u)"

      - name: Create log
        run: |
          echo "Schedule test success" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schedule-test
          path: test.txt